// Generated by scripts/optimize-images.mjs. Do not edit by hand; re-run the script instead.
// Each entry lists the widths available as /images/sdl/<name>-<width>.webp and .jpg.
export interface SdlImageInfo {
  width: number;
  height: number;
  widths: number[];
}

export const SDL_IMAGES = {
  'hero-home': { width: 1671, height: 940, widths: [640, 1024, 1600] },
  'hero-home-mobile': { width: 940, height: 1671, widths: [640, 940] },
  'track-hero': { width: 1672, height: 836, widths: [640, 1024, 1600] },
  'locations-hero': { width: 1024, height: 512, widths: [640, 1024] },
  'callback-banner': { width: 1672, height: 557, widths: [640, 1024, 1600] },
  'service-priority-express': { width: 340, height: 340, widths: [340] },
  'service-freight-linehaul': { width: 340, height: 340, widths: [340] },
  'service-vehicle-transport': { width: 340, height: 340, widths: [340] },
  'service-secure-vault': { width: 340, height: 340, widths: [340, 640] },
  'industry-healthcare': { width: 340, height: 340, widths: [340, 640] },
  'industry-technology': { width: 340, height: 340, widths: [340, 640] },
  'industry-automotive': { width: 340, height: 340, widths: [340] },
  'industry-ecommerce': { width: 340, height: 340, widths: [340] },
  'track-result-vehicle': { width: 340, height: 340, widths: [340] },
  'about-operations': { width: 340, height: 340, widths: [340] },
  'contact-team': { width: 340, height: 340, widths: [340] },
  'about-team': { width: 262, height: 262, widths: [262] },
} satisfies Record<string, SdlImageInfo>;

export type SdlImageName = keyof typeof SDL_IMAGES;
